[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
idl_example = "HtVhuiF23oEMx1nMhqmLcL1eNKeQ8vz2UnbzhPE9ek1v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pileks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
