name: generate-verifiable-build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-verifiable-idl_example:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-verifiable-build@v0.2
        with:
          program: idl_example
          anchor-version: '0.29.0'
          solana-cli-version: '1.16.8'
      - run: 'git pull --rebase'
      - run: cp target/deploy/idl_example.so ./verifiable-builds
      - run: cp target/idl/idl_example.json ./verifiable-builds
      - name: Commit verifiable build back to mainline
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'Update idl_example verifiable build'