name: generate-verifiable-build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-verifiable-idl_example:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/anchor-verifiable-build
        with:
          program: idl_example
          anchor-version: '0.29.0'
          solana-cli-version: '2.1.14'
      - run: 'git pull --rebase'
      - run: mkdir -p verifiable-builds
      - run: cp target/deploy/idl_example.so ./verifiable-builds/idl_example.so
      - run: cp target/idl/idl_example.json ./verifiable-builds/idl_example.json
      - name: Commit verifiable build back to mainline
        uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: 'Update idl_example verifiable build'
      - name: Deploy verifiable build buffer and IDL
        id: deploy-verifiable-buffer
        uses: ./.github/actions/deploy-verifiable-buffer
        with:
          network: devnet
          keypair: ${{ secrets.DEPLOY_KEYPAIR }}
          program: idl_example
          program-id: HtVhuiF23oEMx1nMhqmLcL1eNKeQ8vz2UnbzhPE9ek1v
          buffer-authority: 2SG7fCnreQ9wHoqQC7U6pfDN2rYmBqExKuqcGR3StrZW
      - name: Log buffer and IDL addresses
        run: |
          echo "Buffer address: ${{ steps.deploy-verifiable-buffer.outputs.buffer }}"
          echo "IDL address: ${{ steps.deploy-verifiable-buffer.outputs.idl-buffer }}"
